name: Determine composer cache directory on Windows

runs:
  using: composite

  steps:
    - name: Determine composer cache directory on Windows
      shell: pwsh
      run: echo "COMPOSER_CACHE_DIR=~\AppData\Local\Composer" | Out-File -FilePath $env:GITHUB_ENV -Encoding utf8 -Append
